---

- name: Create target directory
  file: path=host_vars/{{inventory_hostname}} state=directory 

- name: Generate Underlay YAML
  template: >
    src=main.conf.j2
    dest=host_vars/{{inventory_hostname}}/generated-underlay-ebgp.yaml
