---
- name: Generate variables
  hosts: [spine,leaf]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    generate_p2p:
      nbr_networks: 40
      network_size: 31
      network_pool: 172.16.0.0/24
    generate_tenant:
      nbr_tenant: 2
      nbr_vni_tenant: 5
      tenant_start_id: 10
      vlan_start: 100
      vni_prefix: 9
      network_pool: 10.0.0.0/16
      network_size: 24
  roles:
    - generate-p2p-ips
    - generate-tenant-vni

- name: Generate variables for underlay
  hosts: [spine, leaf, fabric]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
    - meta: refresh_inventory
  roles:
    - generate-underlay-bgp
